server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://44.215.241.158"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: ms-usuarios
          uri: http://ms-usuario:8085
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: ms-alertas
          uri: http://ms-alertas:8083
          predicates:
            - Path=/api/alerts/**

        - id: ms-reportes
          uri: http://ms-reportes:8084
          predicates:
            - Path=/api/reports/**
          filters:
            - RewritePath=/api/reports(?<segment>/?.*), /api/reportes$\{segment}

        - id: ms-monitoreo
          uri: http://ms-monitoreo:8082
          predicates:
            - Path=/api/monitoreo/**